# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws', models.NullBooleanField(default=False)),
                ('st2api', models.NullBooleanField(default=False)),
                ('pci', models.NullBooleanField(default=False)),
                ('hipaa', models.NullBooleanField(default=False)),
                ('nist', models.NullBooleanField(default=False)),
                ('scanner', models.NullBooleanField(default=False)),
                ('azure', models.NullBooleanField(default=False)),
                ('ssh', models.NullBooleanField(default=False)),
                ('onboard', models.NullBooleanField(default=False)),
                ('asset_pulled', models.NullBooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyAccount')),
            ],
        ),
    ]
