# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secberus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='userpics/userAvatar.png', upload_to='userpics')),
                ('admin', models.BooleanField(default=False)),
                ('securityOfficial', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('Security', 'Security'), ('Compliance', 'Compliance'), ('Staff', 'Staff'), ('Auditor', 'Auditor')], max_length=10, null=True)),
                ('temp_password', models.BooleanField(default=False)),
                ('disable', models.BooleanField(default=False)),
                ('active_company', models.IntegerField(null=True)),
                ('trial_period', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyAccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
