# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secberus', '0002_accountprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='accountprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountProfile',
        ),
    ]
