# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_auto_20180604_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='company',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='user',
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
